name: androidstudio_project
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  camerawesome: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
     - assets/meta_logo.png
     - assets/app_logo.png
     - assets/like_icon.png
     - assets/message_icon.png
     - assets/name_logo.jpg
     - assets/name_logo_1.png
     - assets/home_icon.png
     - assets/home_icon_2.png
     - assets/image-1.jpg
     - assets/image-2.jpg
     - assets/image-3.jpg
     - assets/image-4.jpg
     - assets/image-5.jpg
     - assets/image-6.jpg



